const notes = [
  {
    title: 'my next trip',
    body: 'I would like to go to Spain'
  },
  {
    title: 'Habits to work on',
    body: 'Excersise. Eating a bit better.'
  },
  {
    title: 'Office modification',
    body: 'Get a new seat'
  }
];

const p = document.querySelectorAll('p');
console.log(p);

p.forEach(p => console.log(p.textContent));

const newP = document.createElement('p');
newP.textContent = 'This is a new element generated by JavaScript';
document.querySelector('body').appendChild(newP);
